.TH hellotest 1 "January 2011" "1.1 Linux Version" "User Manuals"
.SH NAME
hellotest \- Application that prints "hello world"
.SH SYNOPSIS
hellotest [--debug][-n #]
.SH DESCRIPTION
.B hellotest 1.1

hellotest allows you to print “Hello World” from the command. This is done as practice in many languages as the first application written. 
.SH OPTIONS
.IP --debug
Print verbose runtime information to the terminal that can be used for debugging purposes.
.IP -n 
When followed by a number this is the number of times hello world will be printed to the terminal. 
.SH BUGS
See http://myDebuggingSiteForHello.org.net.edu for a current list of bugs or email new bugs to myDebug@debug.org.net.edu.edu.mail.net.org 
.SH "SEE ALSO"
.B gcc(1), g++(1), goodbye-world(1)
