.TH practical 1 "January 2012" "1.1 Linux Version" "User Manuals"
.SH NAME
practical \- Build automation script for practical

.SH SYNOPSIS
practical [--no-output]
.SH DESCRIPTION
.B practical 1.1

practical is a build automation script for the practical. It builds all of the practical files and executes them with output. 
.SH OPTIONS
.IP --no-output
Does not print any output when the script is run, but still builds and executes the files 
.IP --only-completion 
Only prints out the build architecture information
.SH BUGS
Contact myUsername@ rit.edu for any bugs in the program 
.SH "SEE ALSO"
.B gcc(1), g++(1), javac(1), python(1), perl(1) 
