######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 20 00:00:01 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Hello.c Hello.cpp QtTest.cpp ThreadTest.cpp
