Document: hellotestdeb
Title: Debian hellotestdeb Manual
Author: <insert document author here>
Abstract: This manual describes what hellotestdeb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hellotestdeb/hellotestdeb.sgml.gz

Format: postscript
Files: /usr/share/doc/hellotestdeb/hellotestdeb.ps.gz

Format: text
Files: /usr/share/doc/hellotestdeb/hellotestdeb.text.gz

Format: HTML
Index: /usr/share/doc/hellotestdeb/html/index.html
Files: /usr/share/doc/hellotestdeb/html/*.html
