Document: hellotest
Title: Debian hellotest Manual
Author: <insert document author here>
Abstract: This manual describes what hellotest is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hellotest/hellotest.sgml.gz

Format: postscript
Files: /usr/share/doc/hellotest/hellotest.ps.gz

Format: text
Files: /usr/share/doc/hellotest/hellotest.text.gz

Format: HTML
Index: /usr/share/doc/hellotest/html/index.html
Files: /usr/share/doc/hellotest/html/*.html
